require "./spec_helper"

# Fails every COMMIT, as a server does when e.g. a deferred constraint is violated.
class FailingCommitConnection < MockConnection
  def perform_commit_transaction
    raise DB::Error.new "commit failed"
  end
end

struct ConnectionTest < ASPEC::TestCase
  @wrapped : MockConnection
  @connection : AORM::Connection

  def initialize
    @wrapped = MockConnection.new
    @connection = AORM::Connection.new @wrapped
  end

  def test_platform_is_picked_by_the_driver_of_the_wrapped_connection : Nil
    @connection.driver.should be_a AORM::Driver::SQLite3
    @connection.platform.should be_a AORM::Platforms::SQLite

    connection = AORM::Connection.new MockConnection.new(driver_name: "mysql", server_name: "MariaDB")
    connection.driver.should be_a AORM::Driver::MySQL
    connection.platform.should be_a AORM::Platforms::Maria
  end

  def test_given_driver_is_used_instead_of_the_wrapped_connections : Nil
    connection = AORM::Connection.new @wrapped, AORM::Driver::Postgres.new

    connection.driver.should be_a AORM::Driver::Postgres
    connection.platform.should be_a AORM::Platforms::Postgres
  end

  def test_unknown_driver_raises : Nil
    expect_raises AORM::Exceptions::UnknownDriver, %(The given driver "oracle" is unknown, the ORM currently supports only the following drivers: postgres, mysql, sqlite3.) do
      AORM::Connection.new MockConnection.new(driver_name: "oracle")
    end
  end

  def test_statements_are_prepared_by_the_driver : Nil
    wrapped = MockConnection.new driver_name: "postgres"
    AORM::Connection.new(wrapped).exec "UPDATE t SET a = ? WHERE b = ?", 1, 2

    wrapped.built_statements.last.should eq "UPDATE t SET a = $1 WHERE b = $2"
  end

  def test_last_insert_id_is_the_identifier_the_last_executed_statement_generated : Nil
    @wrapped.push_ids 42
    @connection.exec "INSERT INTO t (a) VALUES (?)", 1

    @connection.last_insert_id.should eq 42
  end

  def test_last_insert_id_raises_when_the_last_executed_statement_generated_none : Nil
    @wrapped.push_ids 42
    @connection.exec "INSERT INTO t (a) VALUES (?)", 1
    @connection.exec "UPDATE t SET a = ?", 2

    expect_raises AORM::Exceptions::NoIdentityValue, "No identity value was generated by the last statement." do
      @connection.last_insert_id
    end
  end

  def test_convert_to_database_value_uses_the_registered_type : Nil
    @connection.convert_to_database_value("abc", Rot13Type::NAME).should eq "nop"
  end

  def test_convert_to_database_value_passes_untyped_values_through : Nil
    @connection.convert_to_database_value("abc", nil).should eq "abc"
  end

  def test_execute_statement_binds_parameters_converted_through_their_types : Nil
    @connection.execute_statement "UPDATE t SET a = ?, b = ? WHERE c = ?", ["abc", 7, "xyz"], [Rot13Type::NAME, nil, Rot13Type::NAME]

    @wrapped.executed_statements.last.should eq({"UPDATE t SET a = ?, b = ? WHERE c = ?", ["nop", 7, "klm"]})
  end

  # A boxed value object converts through its type before binding.
  def test_execute_statement_binds_boxed_values_converted_through_their_types : Nil
    param = AORM::Mapping::SingleValue.new AORM::Mapping.box(CustomIdObject.new("abc"))

    @connection.execute_statement "UPDATE t SET a = ?", [param], [CustomIdObjectType::NAME]

    @wrapped.executed_statements.last.should eq({"UPDATE t SET a = ?", ["abc"]})
  end

  def test_execute_statement_returns_the_affected_row_count : Nil
    @connection.execute_statement("DELETE FROM t", [] of DB::Any, [] of String?).should eq 1
  end

  def test_execute_query_binds_parameters_converted_through_their_types : Nil
    @connection.execute_query("SELECT * FROM t WHERE a = ?", ["abc"], [Rot13Type::NAME]) { }

    @wrapped.executed_statements.last.should eq({"SELECT * FROM t WHERE a = ?", ["nop"]})
  end

  def test_execute_query_returns_the_block_value : Nil
    @connection.execute_query("SELECT 1", [] of DB::Any, [] of String?) { :done }.should eq :done
  end

  def test_execute_query_without_a_block_returns_the_result_set : Nil
    rs = @connection.execute_query "SELECT * FROM t WHERE a = ?", ["abc"], [Rot13Type::NAME]
    rs.close

    @wrapped.executed_statements.last.should eq({"SELECT * FROM t WHERE a = ?", ["nop"]})
  end

  def test_fetch_one_returns_the_first_column_of_the_first_row : Nil
    @wrapped.queue_result [{"c" => 3_i64, "d" => 4_i64} of String => DB::Any]

    @connection.fetch_one("SELECT c, d FROM t WHERE a = ?", ["abc"], [Rot13Type::NAME]).should eq 3_i64
    @wrapped.executed_statements.last[1].should eq ["nop"]
  end

  def test_fetch_one_returns_nil_without_rows : Nil
    @wrapped.queue_result [] of Hash(String, DB::Any)

    @connection.fetch_one("SELECT c FROM t", [] of DB::Any, [] of String?).should be_nil
  end

  def test_nested_transactions_are_savepoints : Nil
    @connection.begin_transaction
    @connection.begin_transaction

    @connection.transaction_nesting_level.should eq 2

    @connection.commit
    @connection.transaction_active?.should be_true

    @connection.commit
    @connection.transaction_active?.should be_false

    @wrapped.built_statements[0].should eq "BEGIN"
    @wrapped.built_statements[1].should start_with "SAVEPOINT "
    @wrapped.built_statements[2].should start_with "RELEASE SAVEPOINT "
    @wrapped.built_statements[3].should eq "COMMIT"
  end

  def test_rolling_back_a_nested_transaction_keeps_the_outer_one : Nil
    @connection.begin_transaction
    @connection.begin_transaction
    @connection.rollback

    @connection.transaction_nesting_level.should eq 1
    @wrapped.built_statements.last.should start_with "ROLLBACK TO "

    @connection.rollback
    @connection.transaction_active?.should be_false
    @wrapped.built_statements.last.should eq "ROLLBACK"
  end

  def test_commit_without_a_transaction_raises : Nil
    expect_raises DB::Error, "There is no active transaction." do
      @connection.commit
    end
  end

  def test_rollback_without_a_transaction_raises : Nil
    expect_raises DB::Error, "There is no active transaction." do
      @connection.rollback
    end
  end

  def test_failed_commit_ends_the_transaction : Nil
    connection = AORM::Connection.new FailingCommitConnection.new
    connection.begin_transaction

    expect_raises DB::Error, "commit failed" do
      connection.commit
    end

    connection.transaction_active?.should be_false

    # The driver no longer considers a transaction open either.
    connection.begin_transaction
    connection.transaction_active?.should be_true
  end

  def test_transactional_commits_and_returns_the_block_value : Nil
    @connection.transactional(&.transaction_active?).should be_true

    @connection.transaction_active?.should be_false
    @wrapped.built_statements.last.should eq "COMMIT"
  end

  def test_transactional_rolls_back_when_the_block_raises : Nil
    expect_raises Exception, "boom" do
      @connection.transactional { raise "boom" }
    end

    @connection.transaction_active?.should be_false
    @wrapped.built_statements.last.should eq "ROLLBACK"
  end

  def test_transactional_nests_as_a_savepoint : Nil
    @connection.begin_transaction
    @connection.transactional { }

    @connection.transaction_nesting_level.should eq 1
    @wrapped.built_statements.last.should start_with "RELEASE SAVEPOINT "
  end
end
