INHERIT: ../../../mkdocs-common.yml

site_name: Mercure

nav:
  - Introduction: README.md
  - Back to Manual: project://.
  - API:
    - Top Level: top_level.md
    - Aliases: aliases.md
    - '*'

plugins:
  - search
  - section-index
  - literate-nav
  - gen-files:
      scripts:
        - ../../../gen_doc_stubs.py
  - mkdocstrings:
      default_handler: crystal
      custom_templates: ../../../docs/templates
      handlers:
        crystal:
          crystal_docs_flags:
            - ./docs/index.cr
            - ./lib/athena-mercure/src/athena-mercure.cr
            - ./lib/athena-mercure/src/spec.cr
