INHERIT: ../../../mkdocs-common.yml

site_name: Mercure
site_url: https://athenaframework.org/Mercure/
repo_url: https://github.com/athena-framework/mercure

nav:
  - Introduction: README.md
  - Back to Manual: project://.
  - API:
    - Aliases: aliases.md
    - Top Level: top_level.md
    - '*'

plugins:
  - search
  - section-index
  - literate-nav
  - gen-files:
      scripts:
        - ../../../gen_doc_stubs.py
  - mkdocstrings:
      default_handler: crystal
      custom_templates: ../../../docs/templates
      handlers:
        crystal:
          crystal_docs_flags:
            - ../../../docs/index.cr
            - ../../../lib/athena-mercure/src/athena-mercure.cr
            - ../../../lib/athena-mercure/src/spec.cr
          source_locations:
            lib/athena-mercure: https://github.com/athena-framework/mercure/blob/v{shard_version}/{file}#L{line}
