[default]
extend-ignore-re = [
  "(?Rm)^.*#\\s*spellchecker:disable-line$", # All disabling specific lines
  "[=0-9A-F \n\r]{2}", # Disable checking Quoted-Printable encoded strings
]

[default.extend-words]
referer = "referrer"

[files]
extend-exclude = [
  "src/components/routing/spec/fixtures/route_provider/*",
  "src/components/mime/src/types/data.cr",
  "src/components/mime/spec/fixtures/*",
]
