[default]
extend-ignore-re = ["(?Rm)^.*#\\s*spellchecker:disable-line$"]

[default.extend-words]
referer = "referrer"

[files]
extend-exclude = [
  "src/components/routing/spec/fixtures/route_provider/*"
]
