comment:
  layout: 'condensed_header, components, condensed_files, condensed_footer'

coverage:
  status:
    project:
      default:
        target: auto # Prevent total coverage from decreasing due to a PR
    patch:
      default:
        target: 100% # Enforce all _new_ code is fully tested

component_management:
  individual_components:
    # Bundles
    - component_id: mercure_bundle
      name: Mercure Bundle
      paths:
        - src/bundles/mercure/**

    # Components
    - component_id: clock_component
      name: Clock Component
      paths:
        - src/components/clock/**
    - component_id: console_component
      name: Console Component
      paths:
        - src/components/console/**
    - component_id: dependency_injection_component
      name: Dependency Injection Component
      paths:
        - src/components/dependency_injection/**
    - component_id: dotenv_component
      name: Dotenv Component
      paths:
        - src/components/dotenv/**
    - component_id: event_dispatcher_component
      name: Event Dispatcher Component
      paths:
        - src/components/event_dispatcher/**
    - component_id: framework_component
      name: Framework Component
      paths:
        - src/components/framework/**
    - component_id: http_component
      name: HTTP Component
      paths:
        - src/components/http/**
    - component_id: http_kernel_component
      name: HTTP Kernel Component
      paths:
        - src/components/http_kernel/**
    - component_id: image_size_component
      name: Image Size Component
      paths:
        - src/components/image_size/**
    - component_id: mercure_component
      name: Mercure Component
      paths:
        - src/components/mercure/**
    - component_id: mime_component
      name: MIME Component
      paths:
        - src/components/mime/**
    - component_id: negotiation_component
      name: Negotiation Component
      paths:
        - src/components/negotiation/**
    - component_id: routing_component
      name: Routing Component
      paths:
        - src/components/routing/**
    - component_id: serializer_component
      name: Serializer Component
      paths:
        - src/components/serializer/**
    - component_id: spec_component
      name: Spec Component
      paths:
        - src/components/spec/**
    - component_id: validator_component
      name: Validator Component
      paths:
        - src/components/validator/**
