INHERIT: ../../../mkdocs-common.yml

site_name: MIME
site_url: https://athenaframework.org/MIME/
repo_url: https://github.com/athena-framework/mime

nav:
  - Introduction: README.md
  - Back to Manual: project://.
  - API:
    - Aliases: aliases.md
    - Top Level: top_level.md
    - '*'

plugins:
  - search
  - section-index
  - literate-nav
  - gen-files:
      scripts:
        - ../../../gen_doc_stubs.py
  - mkdocstrings:
      default_handler: crystal
      custom_templates: ../../../docs/templates
      handlers:
        crystal:
          crystal_docs_flags:
            - ../../../docs/index.cr
            - ../../../lib/athena-mime/src/athena-mime.cr
          source_locations:
            lib/athena-mime: https://github.com/athena-framework/mime/blob/v{shard_version}/{file}#L{line}
