name: Deploy docs
on: [push, pull_request]
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
        with:
          crystal: nightly
      - name: Install Python
        uses: actions/setup-python@v2
      - name: Install Python libs
        run: pip install --no-deps -r requirements.txt
      - name: Install Crystal libs
        run: shards install
      - name: Build site
        run: mkdocs build --strict
      - name: Deploy to gh-pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: mkdocs gh-deploy --force
