INHERIT: ../../../mkdocs-common.yml

site_name: Config

nav:
  - Introduction:
    - Introduction: index.md
    - Back to Manual: project://.
  - API:
    - Top Level: top_level.md
    - Aliases: aliases.md
    - '*'

plugins:
  - search
  - literate-nav
  - gen-files:
      scripts:
        - ../../../gen_doc_stubs.py
  - mkdocstrings:
      default_handler: crystal
      custom_templates: ../../../docs/templates
      handlers:
        crystal:
          crystal_docs_flags:
            - ./docs/index.cr
            - ./lib/athena-config/src/athena-config.cr
