name: athena-config

version: 0.3.2

crystal: ~> 1.4

license: MIT

repository: https://github.com/athena-framework/config

documentation: https://athenaframework.org/Config

description: |
  Common library for configuring Athena components.

authors:
  - George Dietrich <george@dietrich.app>
