# Value-object identifier generated by the database and read back from the INSERT.
@[AORMA::Entity]
@[AORMA::Table(name: "custom_id_type_generated")]
class CustomIdObjectTypeGenerated < AORM::Entity
  @[AORMA::Column(type: "CustomIdObject")]
  @[AORMA::ID]
  @[AORMA::GeneratedValue]
  property! id : CustomIdObject

  @[AORMA::Column]
  property! name : String
end
