INHERIT: ../../../mkdocs-common.yml

site_name: Contracts
site_url: https://athenaframework.org/Contracts/
repo_url: https://github.com/athena-framework/contracts

nav:
  - Introduction: README.md
  - Back to Manual: project://.
  - API:
      - '*'

plugins:
  - search
  - section-index
  - literate-nav
  - gen-files:
      scripts:
        - ../../../gen_doc_stubs.py
  - mkdocstrings:
      default_handler: crystal
      custom_templates: ../../../docs/templates
      handlers:
        crystal:
          crystal_docs_flags:
            - ../../../docs/index.cr
            - ../../../lib/athena-contracts/src/athena-contracts.cr
          source_locations:
            lib/athena-contracts: https://github.com/athena-framework/contracts/blob/v{shard_version}/{file}#L{line}
