require "../driver"
require "../sql/parser"

# The `postgres` driver shard ([will/crystal-pg](https://github.com/will/crystal-pg)), using `AORM::Platforms::Postgres`.
#
# The shard only accepts numbered parameter placeholders (`$1`, `$2`, ...), so the `?` placeholders in statements are numbered when they're prepared.
# It doesn't report generated identifiers either, so `#last_insert_id` asks the server.
struct Athena::ORM::Driver::Postgres < Athena::ORM::Driver
  # :inherit:
  def database_platform(connection : DB::Connection) : Platforms::Platform
    Platforms::Postgres.new
  end

  # :inherit:
  def prepare(connection : DB::Connection, sql : String) : DB::Statement
    visitor = SQL::ConvertParameters.new
    SQL::Parser.new(false).parse(sql, visitor)

    super connection, visitor.sql
  end

  # :inherit:
  #
  # Returns the value most recently generated by a sequence in *connection*'s session (`SELECT LASTVAL()`).
  # The driver shard raises if no sequence was used yet.
  def last_insert_id(connection : DB::Connection, reported_id : Int64) : Int64
    connection.scalar("SELECT LASTVAL()").as Int64
  end
end
