# Base platform for Postgres.
#
# Database-generated identifiers are read back with `INSERT ... RETURNING`.
# Queries run through an `AORM::Connection`, such as native queries, may use `?` placeholders, which are rewritten to `$1`, `$2`, etc. before being sent to the server.
class Athena::ORM::Platforms::Postgres < Athena::ORM::Platforms::Platform
  # Boolean string literals Postgres accepts in text contexts (e.g. when a
  # value arrives as a string from a hand-rolled query). Anything else falls
  # through to the parent overloads, where `Bool` and `Int` are handled.
  private FALSE_LITERALS = ["f", "false", "n", "no", "off", "0"]

  # Converts *value*, a boolean literal such as `"t"` or `"off"`, into a `Bool`.
  def convert_from_boolean(value : ::String) : Bool
    !FALSE_LITERALS.includes? value.strip.downcase
  end

  # SQL Declarations

  # :inherit:
  def boolean_type_declaration_sql(column : Schema::Column) : String
    "BOOLEAN"
  end

  # :inherit:
  def small_int_type_declaration_sql(column : Schema::Column) : String
    "SMALLINT#{self.common_integer_type_declaration_sql column}"
  end

  # :inherit:
  def integer_type_declaration_sql(column : Schema::Column) : String
    "INT#{self.common_integer_type_declaration_sql column}"
  end

  # :inherit:
  def big_int_type_declaration_sql(column : Schema::Column) : String
    "BIGINT#{self.common_integer_type_declaration_sql column}"
  end

  # :inherit:
  #
  # Postgres declares a native `UUID` column.
  def guid_type_declaration_sql(column : Schema::Column) : String
    "UUID"
  end

  # :inherit:
  def blob_type_declaration_sql(column : Schema::Column) : String
    "BYTEA"
  end

  # :inherit:
  def date_time_type_declaration_sql(column : Schema::Column) : String
    "TIMESTAMP(0) WITHOUT TIME ZONE"
  end

  protected def binary_type_declaration_sql_snippet(length : Int32?) : String
    "BYTEA"
  end

  protected def varbinary_type_declaration_sql_snippet(length : Int32?) : String
    "BYTEA"
  end

  # A length is optional for `VARCHAR` columns on Postgres.
  private def varchar_type_declaration_sql(length : Int32?) : String
    length ? "VARCHAR(#{length})" : "VARCHAR"
  end

  private def common_integer_type_declaration_sql(column : Schema::Column) : String
    if column.auto_increment?
      return " GENERATED BY DEFAULT AS IDENTITY"
    end

    ""
  end

  # :inherit:
  def sequence_next_value_sql(sequence_name : String) : String
    "SELECT NEXTVAL('#{sequence_name}')"
  end

  # :inherit:
  def empty_identity_insert_sql(quoted_table_name : String, quoted_identifier_column_name) : String
    "INSERT INTO #{quoted_table_name} (#{quoted_identifier_column_name}) VALUES (DEFAULT)"
  end

  # :inherit:
  def supports_returning? : Bool
    true
  end
end
