require "./spec_helper"

# The behavior drivers share unless they override it, through a driver that doesn't.
struct DriverTest < ASPEC::TestCase
  @connection : MockConnection = MockConnection.new
  @driver : AORM::Driver = AORM::Driver::SQLite3.new

  def test_prepare_builds_the_statement_as_is : Nil
    @driver.prepare @connection, "SELECT * FROM t WHERE a = ?"

    @connection.built_statements.last.should eq "SELECT * FROM t WHERE a = ?"
  end

  def test_last_insert_id_is_the_identifier_the_driver_shard_reported : Nil
    @driver.last_insert_id(@connection, 6_i64).should eq 6
  end

  def test_last_insert_id_raises_when_no_identifier_was_reported : Nil
    expect_raises AORM::Exceptions::NoIdentityValue, "No identity value was generated by the last statement." do
      @driver.last_insert_id @connection, 0_i64
    end
  end
end
