INHERIT: ../../../mkdocs-common.yml

site_name: Clock

nav:
  - Introduction:
    - index.md
    - Back to Manual: project://.
  - API:
    - Top Level: top_level.md
    - Aliases: aliases.md
    - '*'

extra_css:
  - ../../../css/index.css
  - ../../../css/component.css

plugins:
  - search
  - literate-nav
  - gen-files:
      scripts:
        - ../../../gen_doc_stubs.py
  - mkdocstrings:
      default_handler: crystal
      handlers:
        crystal:
          crystal_docs_flags:
            - ./docs/index.cr
            - ./lib/athena-clock/src/athena-clock.cr
            - ./lib/athena-clock/src/spec.cr
