INHERIT: ../../../mkdocs-common.yml

site_name: Clock
use_directory_urls: true

nav:
  - Back to Manual: project://.
  - Clock:
    - index.md
    - Aliases: aliases.md
    - './*'

strict: false

validation:
  absolute_links: ignore
  unrecognized_links: ignore

extra:
  homepage: project://.

plugins:
  - search
  - literate-nav  # Allows using the `./*` wildcard
  - section-index # Allows
  - gen-files:
      scripts:
        - ../../../gen_doc_stubs.py
  - mkdocstrings:
      default_handler: crystal
      handlers:
        crystal:
          crystal_docs_flags:
            - ./src/components/clock/src/athena-clock.cr
            - ./src/components/clock/src/spec.cr
