INHERIT: ../../../mkdocs-common.yml

site_name: Clock
use_directory_urls: true

nav:
  - Clock:
    - index.md
    - Aliases: aliases.md
    - './*'

plugins:
  - search
  - literate-nav
  - section-index
  - gen-files:
      scripts:
        - ../../../gen_doc_stubs.py
  - mkdocstrings:
      default_handler: crystal
      handlers:
        crystal:
          crystal_docs_flags:
            - ./src/components/clock/src/athena-clock.cr
            - ./src/components/clock/src/spec.cr
