INHERIT: ../../../mkdocs-common.yml

site_name: Framework
site_url: https://athenaframework.org/Framework/
repo_url: https://github.com/athena-framework/framework

nav:
  - Back to Manual: project://.
  - API:
    - Aliases: aliases.md
    - Top Level: index.md
    - '*'

plugins:
  - search
  - section-index
  - literate-nav
  - gen-files:
      scripts:
        - ../../../gen_doc_stubs.py
  - mkdocstrings:
      default_handler: crystal
      custom_templates: ../../../docs/templates
      handlers:
        crystal:
          crystal_docs_flags:
            - ./docs/index.cr
            - ./lib/athena/src/athena.cr
            - ./lib/athena/src/spec.cr
          source_locations:
            lib/athena: https://github.com/athena-framework/framework/blob/v{shard_version}/{file}#L{line}
