site_name: Athena
use_directory_urls: true
repo_url: https://github.com/athena-framework/athena
edit_uri: https://github.com/athena-framework/website/blob/master/docs/
site_url: https://athenaframework.org

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark theme
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to light theme
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs

extra_css:
  - css/mkdocstrings.css

plugins:
  - search
  - gen-files:
      scripts:
        - gen_doc_stubs.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      default_handler: crystal
      handlers:
        crystal:
          crystal_docs_flags:
            - lib/athena-spec/src/athena-spec.cr
            - lib/athena-event_dispatcher/src/athena-event_dispatcher.cr
            - lib/athena-console/src/athena-console.cr
            - lib/athena-console/src/spec.cr
            - lib/athena-config/src/athena-config.cr
            - lib/athena-dependency_injection/src/athena-dependency_injection.cr
            - lib/athena-serializer/src/athena-serializer.cr
            - lib/athena-validator/src/athena-validator.cr
            - lib/athena-negotiation/src/athena-negotiation.cr
            - lib/athena-validator/src/spec.cr
            - lib/athena/src/athena.cr
            - lib/athena/src/spec.cr
          source_locations:
            lib/athena-config: https://github.com/athena-framework/config/blob/v{shard_version}/{file}#L{line}
            lib/athena-console: https://github.com/athena-framework/console/blob/v{shard_version}/{file}#L{line}
            lib/athena-dependency_injection: https://github.com/athena-framework/dependency-injection/blob/v{shard_version}/{file}#L{line}
            lib/athena-event_dispatcher: https://github.com/athena-framework/event-dispatcher/blob/v{shard_version}/{file}#L{line}
            lib/athena-negotiation: https://github.com/athena-framework/negotiation/blob/v{shard_version}/{file}#L{line}
            lib/athena-serializer: https://github.com/athena-framework/serializer/blob/v{shard_version}/{file}#L{line}
            lib/athena-spec: https://github.com/athena-framework/spec/blob/v{shard_version}/{file}#L{line}
            lib/athena-validator: https://github.com/athena-framework/validator/blob/v{shard_version}/{file}#L{line}
            lib/athena: https://github.com/athena-framework/athena/blob/v{shard_version}/{file}#L{line}

markdown_extensions:
  - admonition
  - callouts
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.saneheaders
  - pymdownx.superfences
  - deduplicate-toc
  - toc:
      permalink: "#"

extra:
  analytics:
    provider: google
    property: UA-184169799-1
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/athena-framework
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/athena-frameworkcr/community
    - icon: fontawesome/brands/discord
      link: https://discord.gg/TmDVPb3dmr
