INHERIT: ../../../mkdocs-common.yml

site_name: Dotenv
use_directory_urls: true

# nav:
#   - Dotenv:
#     - index.md
#     - './*'

plugins:
  - search
  - literate-nav
  # - gen-files:
  #     scripts:
  #       - ../../../gen_doc_stubs.py
  - mkdocstrings:
      default_handler: crystal
      handlers:
        crystal:
          crystal_docs_flags:
            - ./src/components/dotenv/src/athena-dotenv.cr
          source_locations:
            src/components/dotenv: https://github.com/athena-framework/dotenv/blob/v{shard_version}/{file}#L{line}

