require "./orm_exception"

# Raised by `AORM::Connection#last_insert_id` when the last statement didn't generate an identifier.
class Athena::ORM::Exceptions::NoIdentityValue < Athena::ORM::Exceptions::ORMException
  def initialize
    super "No identity value was generated by the last statement."
  end
end
