# What the ORM needs to know about a `crystal-db` driver shard, beyond the API `DB::Connection` already shares across shards.
#
# The ORM has one for each supported driver shard, picked by `AORM::DriverManager` from the name the shard registers its connections with (`DB::Connection#driver_name`).
abstract struct Athena::ORM::Driver
  # Returns the platform of the database *connection* is to.
  abstract def database_platform(connection : DB::Connection) : Platforms::Platform

  # Returns the statement executing *sql* on *connection*.
  def prepare(connection : DB::Connection, sql : String) : DB::Statement
    connection.build sql
  end

  # Returns the identifier generated by the last statement executed on *connection*, for which the driver shard reported *reported_id*.
  #
  # Raises `AORM::Exceptions::NoIdentityValue` if that statement didn't generate one.
  def last_insert_id(connection : DB::Connection, reported_id : Int64) : Int64
    raise Exceptions::NoIdentityValue.new if reported_id.zero?

    reported_id
  end
end
