require "../spec_helper"

struct PostgresPlatformBooleanTest < ASPEC::TestCase
  @platform : AORM::Platforms::Postgres = AORM::Platforms::Postgres.new

  @[DataProvider("pg_boolean_provider")]
  def test_convert_booleans_to_db_value_passes_bool_through(_database_value : String, boolean_value : Bool) : Nil
    @platform.convert_booleans_to_db_value(boolean_value).should eq boolean_value
  end

  @[DataProvider("pg_boolean_provider")]
  def test_convert_from_boolean_recognizes_string_literal(database_value : String, boolean_value : Bool) : Nil
    @platform.convert_from_boolean(database_value).should eq boolean_value
  end

  def test_convert_from_boolean_normalizes_whitespace_and_case : Nil
    @platform.convert_from_boolean("  FALSE  ").should eq false
    @platform.convert_from_boolean(" Off ").should eq false
    @platform.convert_from_boolean(" T ").should eq true
  end

  # Anything not in the false-literal set is truthy
  def test_convert_from_boolean_treats_unknown_string_as_true : Nil
    @platform.convert_from_boolean("anything else").should eq true
    @platform.convert_from_boolean("maybe").should eq true
  end

  def test_convert_from_boolean_preserves_nil : Nil
    @platform.convert_from_boolean(nil).should be_nil
  end

  def test_convert_from_boolean_passes_bool_through : Nil
    @platform.convert_from_boolean(true).should eq true
    @platform.convert_from_boolean(false).should eq false
  end

  def test_convert_booleans_to_db_value_raises_on_invalid_literal : Nil
    expect_raises(Exception, /cannot convert.+to a boolean DB value/i) do
      @platform.convert_booleans_to_db_value("my-bool")
    end
  end

  def pg_boolean_provider : Hash
    {
      "string 't'"     => {"t", true},
      "string 'true'"  => {"true", true},
      "string 'y'"     => {"y", true},
      "string 'yes'"   => {"yes", true},
      "string 'on'"    => {"on", true},
      "string '1'"     => {"1", true},
      "string 'f'"     => {"f", false},
      "string 'false'" => {"false", false},
      "string 'n'"     => {"n", false},
      "string 'no'"    => {"no", false},
      "string 'off'"   => {"off", false},
      "string '0'"     => {"0", false},
    }
  end
end

struct PostgresPlatformDeclarationTest < ASPEC::TestCase
  @platform : AORM::Platforms::Postgres = AORM::Platforms::Postgres.new

  def test_integer_declarations : Nil
    @platform.integer_type_declaration_sql(column).should eq "INT"
    @platform.integer_type_declaration_sql(column auto_increment: true).should eq "INT GENERATED BY DEFAULT AS IDENTITY"
    @platform.big_int_type_declaration_sql(column).should eq "BIGINT"
    @platform.big_int_type_declaration_sql(column auto_increment: true).should eq "BIGINT GENERATED BY DEFAULT AS IDENTITY"
  end

  def test_numeric_declarations : Nil
    @platform.small_int_type_declaration_sql(column).should eq "SMALLINT"
    @platform.float_declaration_sql(column).should eq "DOUBLE PRECISION"
    @platform.small_float_declaration_sql(column).should eq "REAL"
    @platform.decimal_type_declaration_sql(column precision: 10, scale: 2).should eq "NUMERIC(10, 2)"
  end

  def test_decimal_declaration_requires_precision_and_scale : Nil
    expect_raises(Exception, "Precision required") { @platform.decimal_type_declaration_sql column }
    expect_raises(Exception, "Scale required") { @platform.decimal_type_declaration_sql column precision: 10 }
  end

  # A length is optional for `VARCHAR` columns on Postgres.
  def test_string_declarations : Nil
    @platform.string_type_declaration_sql(column).should eq "VARCHAR"
    @platform.string_type_declaration_sql(column length: 16).should eq "VARCHAR(16)"
    @platform.string_type_declaration_sql(column fixed: true).should eq "CHAR"
    @platform.string_type_declaration_sql(column length: 16, fixed: true).should eq "CHAR(16)"
  end

  def test_guid_declaration_is_native : Nil
    @platform.guid_type_declaration_sql(column).should eq "UUID"
  end

  def test_date_time_declaration : Nil
    @platform.date_time_type_declaration_sql(column).should eq "TIMESTAMP(0) WITHOUT TIME ZONE"
  end

  def test_binary_declarations_are_bytea : Nil
    @platform.blob_type_declaration_sql(column).should eq "BYTEA"
    @platform.binary_type_declaration_sql(column length: 16).should eq "BYTEA"
  end

  private def column(*, length : Int32? = nil, precision : Int32? = nil, scale : Int32? = nil, fixed : Bool = false, auto_increment : Bool = false) : AORM::Schema::Column
    AORM::Schema::Column.new("c", AORM::Types::Type.get_type("string")).tap do |c|
      c.auto_increment = auto_increment
      c.length = length
      c.precision = precision
      c.scale = scale
      c.fixed = fixed
    end
  end
end
