name: Athena

on:
  pull_request:
    branches:
      - 'master'
  schedule:
    - cron: '37 0 * * *' # Nightly at 00:37

jobs:
  CI:
    uses: athena-framework/actions/.github/workflows/ci.yml@master
