on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Which Cloudflare Pages branch (master | dev) to deploy the docs to'
        type: string
        required: true
  workflow_call:
    inputs:
      branch:
        description: 'Which Cloudflare Pages branch (master | dev) to deploy the docs to'
        type: string
        required: true

jobs:
  build-and-publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0
      - name: Install Crystal
        uses: crystal-lang/install-crystal@46e48b6238ee23b1a6ef08ec39f12fb234676006 # v1.9.3
      - name: Install Crystal Shard Dependencies
        run: shards install --without-development
        env:
          SHARDS_OVERRIDE: ${{ inputs.branch == 'dev' && 'shard.dev.yml' || 'shard.prod.yml' }}
      - uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
      - name: Build Docs
        run: just build-docs
      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@953926a2e2182532811c01a25e53647d93bf07c0 # v4.1.3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./site --project-name=athenaframework --branch=${{ inputs.branch }}
