on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Which Cloudflare Pages branch (master | dev) to deploy the docs to'
        type: string
        required: true
  workflow_call:
    inputs:
      branch:
        description: 'Which Cloudflare Pages branch (master | dev) to deploy the docs to'
        type: string
        required: true

jobs:
  build-and-publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0
      - name: Install Crystal
        uses: crystal-lang/install-crystal@d8ef131ecec0352ce0e39b81b0a6d95def58fe2f # v1.9.2
      - name: Install Crystal Shard Dependencies
        run: shards install --without-development
        env:
          SHARDS_OVERRIDE: ${{ inputs.branch == 'dev' && 'shard.dev.yml' || 'shard.prod.yml' }}
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.0.1
      - name: Build Docs
        run: just build-docs
      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./site --project-name=athenaframework --branch=${{ inputs.branch }}
